# Generated by Django 4.2 on 2024-06-07 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="age",
        ),
        migrations.RemoveField(
            model_name="person",
            name="username",
        ),
        migrations.AddField(
            model_name="person",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="person user",
            ),
            preserve_default=False,
        ),
    ]
