# Generated by Django 4.2 on 2024-06-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_person_age_remove_person_username_person_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
